general {
    col.active_border   = rgba({{ color4 | replace("#", "") }}ee)
    col.inactive_border = rgba({{ color0 | replace("#", "") }}aa)
}

decoration {
    shadow {
        color = rgba({{ background | replace("#", "") }}ee)
    }
}
