-- Generated by wallust — do not edit manually
return {
  base00 = "{{background}}",   -- bg
  base01 = "{{color0}}",       -- bg highlight
  base02 = "{{color8}}",       -- selection
  base03 = "{{color8}}",       -- comments
  base04 = "{{color7}}",       -- dark fg
  base05 = "{{foreground}}",   -- default fg
  base06 = "{{color15}}",      -- light fg
  base07 = "{{color15}}",      -- bright white
  base08 = "{{color1}}",       -- red / errors
  base09 = "{{color9}}",       -- orange / constants
  base0A = "{{color3}}",       -- yellow / classes
  base0B = "{{color2}}",       -- green / strings
  base0C = "{{color6}}",       -- cyan / support
  base0D = "{{color4}}",       -- blue / functions
  base0E = "{{color5}}",       -- purple / keywords
  base0F = "{{color13}}",      -- brown / embedded
}
