source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/theme.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windowrules.conf

# NVIDIA
env = WLR_NO_HARDWARE_CURSORS,1
env = EGL_PLATFORM,wayland
env = OZONE_PLATFORM,wayland
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Bibata-Modern-Classic

general {
    layout = dwindle
    gaps_in = 3
    gaps_out = 3
    border_size = 2
    # border colors are in theme.conf
}

dwindle {
    pseudotile = true
    preserve_split = true
}

input {
    kb_layout = us
    follow_mouse = 1
    special_fallthrough = true
    touchpad {
        natural_scroll = false
    }
}

binds {
    movefocus_cycles_fullscreen = 1
}

cursor {
    no_hardware_cursors = 1
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    font_family = JetBrainsMono Nerd Font
    vfr = 1
    vrr = 1
    enable_swallow = true
}

decoration {
    rounding = 4
    active_opacity = 1.0
    inactive_opacity = 0.92
    blur {
        enabled = true
        size = 6
        passes = 3
        vibrancy = 0.2
        special = true
        new_optimizations = true
    }
    shadow {
        enabled = true
        range = 4
        render_power = 3
    }
}

animations {
    enabled = true
    bezier = myBezier, 0.05, 0.97, 0.05, 0.97
    animation = windows,    1, 4, myBezier
    animation = windowsOut, 1, 4, default, popin 80%
    animation = fade,       1, 4, default
    animation = workspaces, 1, 4, default
}

exec-once = awww-daemon
exec-once = mako
exec-once = hypridle
exec-once = hyprsunset
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = eww daemon && eww open bar
exec-once = bash -c 'sleep 0.5; [ -f ~/.cache/wallust/last-wallpaper ] && ~/.local/bin/set-wallpaper "$(cat ~/.cache/wallust/last-wallpaper)"'
exec-once = spicetify watch -s
exec-once = wl-paste --watch cliphist
