#!/usr/bin/env bash
hyprctl activeworkspace -j | jq '.id'
socat -u UNIX-CONNECT:"${XDG_RUNTIME_DIR}/hypr/${HYPRLAND_INSTANCE_SIGNATURE}/.socket2.sock" STDOUT \
    | while read -r _; do hyprctl activeworkspace -j | jq '.id'; done
